### ISSUE TITLE
Seems like yesterdays release broke the ability to search by specific pokemon in the pastes page

### ISSUE THREAD

**Issue by yotam-cohen** [txfs19260817/falinks-teambuilder#20]
https://www.falinks-teambuilder.com/pastes/vgc/

Previously, I could type in a pokemon name in the "team" text field and it would search for that pokemon and then filter the teams including that pokemon. Now that does not seem to work. Is it just me?

**Comment by txfs19260817** [comment]
Hi there, thank you so much for reporting this bug. The fix has been committed.

<details>
  <summary>Post-mortem</summary>
  
  [Commit link](https://github.com/txfs19260817/falinks-teambuilder/commit/f15732147fe4deb6a2b6bdecf5ae1e1a33a618c7#diff-5e1e7ae142343282ea9cdebf52d081871db9cfff04327a3088dd9abd2541f06a)
  An attempt to make the vgc pastes page size smaller by returning only the species array per team instead of a whole paste. However, I forgot to update the corresponded filter as well.
</details>

Your feedback is highly appreciated! Please let me know for anything else I missed.
