### ISSUE TITLE
Urgent Issue: Pokemon search function for Pokemon with multiple Forms

### ISSUE THREAD

**Issue by VGCPastes** [txfs19260817/falinks-teambuilder#28]
Pokemon search has to **factor in** the multiple forms of the following species, meaning that the search has to be encompassing for the following species!:
1. Maushold -> If I search Maushold, we must retrieve results for Maushold and Maushold-Four
2. Gastrodon and Gastrodon-East
3. Toxtricity and Toxtricity-Low-Key
4. Palafin and Palafin-Hero
5. Dudunsparce and Dudunsparce-Three-Segment
6. Squawkabilly and Squawkabilly-Blue and Squawkabilly-White and Squawkabilly-Yellow

However, these Pokemon must retrieve seperate results:
1. Tatsugiri vs Tatsugiri-Droopy vs Tatsugiri-Stretchy
2. Oricorio vs Oricorio-Pa'u vs Oricorio-Pom-Pom vs Oricorio-Sensu
3. Lycanroc vs Lycanroc-Midnight vs Lycanroc-Dusk
4. Tauros-Paldea-Aqua vs Tauros-Paldea-Blaze

There are other examples of combined search required for the complete pokedex, or when the DLC comes out:
1. Pumpkaboo
2. Gourgeist
3. Zygarde
I might be missing some so we will need to update next time as we go along!

**Comment by txfs19260817** [comment]
Notes for me:

It turns out to be a challenging problem:

- [x] find those species who has different formes
- [ ] use cartesian product to make copies of filterValue arrays (e.g. ["Maushold-Four", "abc"] -> [["Maushold", "abc"], ["Maushold-Four", "abc"]])
- [ ] make multiselect menu to also keep those different formes (current problem:  select "Gastrodon-East" -> "abc": ok; select "abc", then you cannot find "Gastrodon-East" yet "Gastrodon" is still there)

**Comment by txfs19260817** [comment]
Hi @VGCPastes , the fix was deployed. You can do some manual tests. If it goes well then pls close this issue. thx

**Comment by txfs19260817** [comment]
Pls feel free to re-open it if any problems
